### ISSUE TITLE
Line23: -VMName $vms[0].name should be -VMName $vm.name OR outside the foreach loop

### ISSUE THREAD

**Issue by TheMacStack** [sam-cogan/AzureAudit#1]
on line 23 inside the first foreach loop you are specifically grabbing the first object in the $vms array, and you do this on every loop which will always be the same first object in the array and invalidate your tests, it should be -VMName $vm.name to target current VM in pipeline/loop

**Comment by sam-cogan** [comment]
This has now been fixed.
